"""Add_treatment_minutes

Revision ID: 71e7ffaeb2cb
Revises: bd1c27694084
Create Date: 2026-01-01 21:44:12.745245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e7ffaeb2cb'
down_revision: Union[str, Sequence[str], None] = 'bd1c27694084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('total_treatment_minutes', sa.Integer(), nullable=True, comment='Total minutes of treatment assigned/completed'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'total_treatment_minutes')
    # ### end Alembic commands ###
