"""Add_lunch_minutes

Revision ID: b8e04b6181da
Revises: 71e7ffaeb2cb
Create Date: 2026-01-01 21:50:37.733808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e04b6181da'
down_revision: Union[str, Sequence[str], None] = '71e7ffaeb2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('lunch_minutes', sa.Integer(), nullable=True, comment='Minutes taken for lunch/break'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'lunch_minutes')
    # ### end Alembic commands ###
